// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/allow": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Allow CIDR for Recursion",
                "parameters": [
                    {
                        "type": "string",
                        "description": "1.2.3.4/32",
                        "name": "cidr",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/geo/update": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Triggers a download and reload of the MaxMind database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "geo"
                ],
                "summary": "Update GeoIP Database",
                "parameters": [
                    {
                        "type": "string",
                        "description": "URL to .mmdb.gz file",
                        "name": "url",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "GeoDB updated",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/login": {
            "get": {
                "summary": "Login to get JWT",
                "responses": {
                    "200": {
                        "description": "JWT Token",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/zone": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Creates a new DNS zone or updates an existing one with a geo-tag",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "zones"
                ],
                "summary": "Add or Update Zone",
                "parameters": [
                    {
                        "description": "Zone Data",
                        "name": "zone",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.Zone"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Zone updated",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/zones": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "zones"
                ],
                "summary": "Get All Zones",
                "responses": {}
            }
        }
    },
    "definitions": {
        "main.ResourceRecord": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "example.com."
                },
                "ttl": {
                    "type": "integer",
                    "example": 3600
                },
                "type": {
                    "type": "string",
                    "example": "A"
                },
                "value": {
                    "type": "string",
                    "example": "1.2.3.4"
                }
            }
        },
        "main.SOAData": {
            "type": "object",
            "properties": {
                "expire": {
                    "type": "integer",
                    "example": 3600000
                },
                "mbox": {
                    "type": "string",
                    "example": "admin.example.com."
                },
                "minttl": {
                    "type": "integer",
                    "example": 172800
                },
                "ns": {
                    "type": "string",
                    "example": "ns1.example.com."
                },
                "refresh": {
                    "type": "integer",
                    "example": 86400
                },
                "retry": {
                    "type": "integer",
                    "example": 7200
                },
                "serial": {
                    "type": "integer",
                    "example": 2024052501
                }
            }
        },
        "main.Zone": {
            "type": "object",
            "properties": {
                "geo_tag": {
                    "type": "string",
                    "example": "RU"
                },
                "origin": {
                    "type": "string",
                    "example": "example.com."
                },
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.ResourceRecord"
                    }
                },
                "soa": {
                    "$ref": "#/definitions/main.SOAData"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "Введите 'Bearer \u003cваш_токен\u003e'",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Geo-DNS API",
	Description:      "API for managing Geo-tagged DNS zones.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
